name: Primer CI
on : [push, pull]
jobs:
  first-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkcout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor}}" >> $GITHUB_ENV
      - name:  scr
        run: python scr/1-primer_github_actions.py


