name: Run Python Script

on:
  schedule:
    - cron: '* * * * *'  # Se ejecuta cada minuto

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python script
        run: |
          echo "Running Python script..."
          python script.py
          
          # Check or create a log file to count executions
          if [ ! -f "execution_count.txt" ]; then
            echo 0 > execution_count.txt
          fi
          
          count=$(cat execution_count.txt)
          count=$((count + 1))
          echo $count > execution_count.txt
          
          # If executed more than 3 times, stop scheduling
          if [ $count -ge 3 ]; then
            echo "Disabling the workflow after 3 executions."
            echo 'DISABLED=true' >> $GITHUB_ENV
          fi

      - name: Disable Workflow
        if: env.DISABLED == 'true'
        run: |
          echo "Disabling the workflow."
          git checkout -b disable-workflow
          echo '# Workflow disabled after 3 executions' > .github/workflows/trigger.yml
          git add .github/workflows/trigger.yml
          git commit -m "Disable workflow after 3 executions"
          git push origin disable-workflow
          gh api --method PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/${{ github.repository }}/actions/workflows/trigger.yml/disable
