name: Segundo CI

on:
  workflow_run:
    workflows: ["Primer CI"]
    types:
      - completed
  schedule:
    - cron: '*/1 * * * *'  # Ejecutar cada minuto

jobs:
  second-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with write permissions
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0


      - name: Run second script
        if: steps.check.outputs.count != '3'
        run: python scr/2-datetime_now.py


